version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: volsync
      POSTGRES_PASSWORD: volsync
      POSTGRES_DB: volsync
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U volsync -d volsync"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  dbdata:
